config/routes.rb
Pollster::Application.routes.draw do
  resources :polls do
    resources :responses
  end
  match '/responses' => 'polls#index'
  resources :questions
  match '/:slug'      => 'polls#edit'

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :title, :edit_url, :questions_attributes
  
  has_many :votes,      :dependent => :destroy 
  has_many :responses,  :dependent => :destroy
  has_many :questions,  :dependent => :destroy
  
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  
  validates_uniqueness_of :edit_url
  
  #before_save :make_edit_url
  
  # def make_edit_url
  #   self.edit_url = (0...5).map{ (0..9).to_a[rand(10)].to_s+('a'..'z').to_a[rand(26)] }.join
  # end
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :content, :responses_attributes
  
  has_many :responses,  :dependent => :destroy
  has_many :votes,      :dependent => :destroy
  
  #accepts_nested_attributes_for :responses, :reject_if => lambda { |a| a[:text].blank? }, :allow_destroy => true
  
  belongs_to :poll
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :question
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :response
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  
  def index
    @polls = Poll.all
  end
  
  def new
    @poll = Poll.new
    3.times do
      question = @poll.questions.build
      #4.times { question.responses.build }
    end
  end
  
  def create
    @poll = Poll.new(params[:poll])
    @poll.edit_url = make_edit_url
    #@question = Question.new(params[:poll][:questions_attributes])
    # @response = Response.new(params[:responses_attributes])
    if @poll.save #&& @question.save && @response.save
      redirect_to polls_path, :flash => {:success => "Go to localhost:3000/#{@poll.edit_url} to edit your poll. Or go to localhost:3000/polls/#{@poll.id} to vote."}
    else
      flash[:error] = "Something went horribly wrong"
      render :new
    end
  end
  
  def show
    @poll = Poll.find(params[:id])
  end
  
  def edit
    @poll = Poll.find_by_edit_url(params[:slug])
  end
  
  def update
    @poll = Poll.find(params[:id])
    if @poll.update_attributes(params[:poll])
      redirect_to polls_path, :flash => {:success => "Success!"}
    else
      flash[:error] = "Something went horribly wrong"
      render :new
    end
  end
  
  def destroy
    if Poll.Find(params[:id]).destroy
      redirect_to root_path, :flash => {:success => "Poll deleted!"}
    else
      flash[:error] = "Something went horribly wrong"
      render :new
    end
  end
      
  def make_edit_url
    @edit_url = (0...5).map{ (0..9).to_a[rand(10)].to_s+('a'..'z').to_a[rand(26)] }.join
  end
end

app/controllers/questions_controller.rb
# class QuestionsController < ApplicationController
#   
#   def new
#     @question = Question.new
#   end
#   
#   def create
#     @question = Question.new(params[:question])
#     if @question.save
#       flash[:success] = "You added a Question!"
#       redirect_to polls_path
#     else
#       flash[:error] = "Something went horribly wrong"
#       render :new
#     end
#   end
# end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def new
    @response = Response.new
    @questions = Poll.find(params[:poll_id]).questions
  end
  
  def create
    @questions = Poll.find(params[:poll_id]).questions
    @response = Response.new(params[:response])
    if @response.save
      redirect_to poll_response_path, :flash => {:success => "We appreciate your feedback!"}
    else
      flash[:error] = "Something went horribly wrong"
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="flash">
		<%= render 'shared/errors' %>
		<%= yield %>
	</div>

</body>
</html>

app/views/polls/edit.html.erb
<h1>Edit Poll:</h1><br>

<%= form_for @poll do |p| %>
	<%= p.label :title %>
	<%= p.text_field :title %>
	
	<%= p.fields_for :questions do |q| %>
	<%= render 'shared/questions', :p => q %><br>
	<% end %>
	<%= p.submit "Create" %>
<% end %>

app/views/polls/index.html.erb
<h1>Welcome to Pollster!</h1>
<h2>Here are some polls:</h2><br>

<%= link_to "Create a new Poll", new_poll_path %><br>

<% @polls.each do |poll| %>
	<%= link_to "#{poll.title}", poll_path(poll) %><br>
<% end %>

app/views/polls/new.html.erb
<h1>Create a new Poll:</h1>

<%= form_for @poll do |p| %>
	<%= p.label :title %>
	<%= p.text_field :title %>
	
	<%= p.fields_for :questions do |q| %>
	<%= render 'shared/questions', :p => q %><br>
	<% end %>
	<%= p.submit "Create" %>
<% end %>	

app/views/polls/show.html.erb
<h1><%= "#{@poll.title}" %></h1>

<% @poll.questions.each do |question| %>
	<li>
		<%= question.content %>
	</li>
<% end %>

app/views/responses/new.html.erb
<h1>Fill out the Poll below:</h1>

<%= form_for @response do |p| %>
	<%= @questions.each do |question| %>
	<%= p.label "#{question.content}" %>
	<%= p.text_area :text, :rows => 3 %>
	<% end %>
	<%= p.submit "Create" %>
<% end %>

app/views/shared/_errors.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

app/views/shared/_questions.html.erb
<p>
<%= p.label "Question" %>
<%= p.text_field :content %>
<%= p.label "Delete question above" %>
<%= p.check_box :_destroy %>
<p>
<%= p.fields_for :responses do |q| %>
	<%= render 'shared/responses', :p => q %>
<% end %>

app/views/shared/_questions_response.html.erb
<p>
<%= p.label :content, "Question" %>
<%= p.text_area :content, :rows => 3 %>
<%= p.check_box :_destroy %>
<%= p.label :_destroy, "Delete question above" %>
<p>
	<%= p.fields_for :responses do |q| %>
	<%= render 'shared/response', :p => q %><br>
	<% end %>
<p>

app/views/shared/_responses.html.erb
<p>
		<%= p.label :text, "Response" %>
		<%= p.text_field :text %>
		<%= p.check_box :_destroy %>
		<%= p.label :_destroy, "Delete response above" %>
<p>